stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - diabetes.csv
    outs:
      - train.csv
      - test.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - train.csv
    outs:
      - model.pkl

  validate:
    cmd: python validate.py
    deps:
      - validate.py
      - test.csv
      - model.pkl
    metrics:
      - metrics.json
    plots:
      - confusion_matrix.png
