stages:
  validate:
    cmd: python validate.py
    deps:
      - validate.py
      - test.csv
      - model.pkl
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false
      - metrics.json:
          cache: false
          x: branch
          y:
            - accuracy
            - f1_score
            - precision
            - recall
