stages:
  preprocess:
    cmd: python preprocess.py
    deps:
    - preprocess.py
    - diabetes.csv
    outs:
    - train.csv
    - test.csv

  train:
    cmd: python train.py
    deps:
    - train.py
    - train.csv
    outs:
    - model.pkl

